

   javascript:(function(){
     var d=document.createElement('div');
     d.style="position:fixed;top:20%;left:30%;width:40%;background:white;z-index:9999;padding:2em;box-shadow:0 0 10px #000;border-radius:8px;";
     d.innerHTML='<h2>My Popup</h2><p>This is a custom popup!</p><button onclick="this.parentNode.remove()">Close</button>';
     document.body.appendChild(d);
   })();

(function () {
  var existing = document.getElementById('yb-perf-advisor-popup');
  if (existing) existing.remove();

  // Create popup container
  var popup = document.createElement('div');
  popup.id = 'yb-perf-advisor-popup';
  popup.innerHTML = `
    <div class="yb-popup-modal">
      <div class="yb-popup-header">
        <img src="https://assets-global.website-files.com/5f6b7b7b7b7b7b7b7b7b7b7b/5f6b7b7b7b7b7b7b7b7b7b7b_yugabyte-logo.svg" alt="Yugabyte" style="height:28px;vertical-align:middle;margin-right:8px;">
        <span style="font-size:1.3em;font-weight:600;vertical-align:middle;">Yugabyte Performance Advisor</span>
      </div>
      <div class="yb-popup-desc">
        <p style="font-size:0.95em;color:#555;">
          This is a custom LLM for Yugabyte with access to developer docs (docs.yugabyte.com), and all GitHub issues from the past year (github.com/yugabyte/yugabyte-db/issues). Please note that answers are generated by AI and may not be fully accurate.
        </p>
      </div>
      <div class="yb-popup-examples">
        <div>
          <button>What performance issues are here?</button>
          <button>Are there any slow downs here?</button>
        </div>
        <div>
          <button>What is the top SQL here?</button>
          <button>What SQL is using the most CPU?</button>
        </div>
      </div>
      <div class="yb-popup-input">
        <input type="text" placeholder="Ask me a question about Yugabyte..." style="width:90%;padding:0.7em;border-radius:6px;border:1px solid #ccc;font-size:1em;">
        <button style="margin-left:8px;padding:0.7em 1em;border-radius:6px;background:#f5f5f5;border:1px solid #ccc;cursor:pointer;">→</button>
      </div>
      <div class="yb-popup-footer">
        <span style="font-size:0.8em;color:#aaa;">powered by kapa.ai</span>
        <span style="float:right;font-size:0.8em;color:#aaa;">protected by reCAPTCHA</span>
      </div>
      <button class="yb-popup-close" title="Close">&times;</button>
    </div>
  `;

  // Add styles
  var style = document.createElement('style');
  style.textContent = `
    #yb-perf-advisor-popup {
      position: fixed;
      top: 0; left: 0; width: 100vw; height: 100vh;
      background: rgba(0,0,0,0.18);
      z-index: 99999;
      display: flex; align-items: center; justify-content: center;
    }
    .yb-popup-modal {
      background: #fff;
      border-radius: 14px;
      box-shadow: 0 8px 32px rgba(0,0,0,0.18);
      padding: 32px 32px 18px 32px;
      min-width: 380px;
      max-width: 420px;
      position: relative;
      font-family: 'Inter', Arial, sans-serif;
    }
    .yb-popup-header {
      display: flex; align-items: center; margin-bottom: 10px;
    }
    .yb-popup-desc {
      margin-bottom: 18px;
    }
    .yb-popup-examples {
      margin-bottom: 18px;
    }
    .yb-popup-examples button {
      margin: 6px 8px 6px 0;
      padding: 10px 14px;
      border-radius: 7px;
      border: 1px solid #e0e0e0;
      background: #fafafa;
      cursor: pointer;
      font-size: 1em;
      transition: background 0.2s;
    }
    .yb-popup-examples button:hover {
      background: #f0f0f0;
    }
    .yb-popup-input {
      display: flex; align-items: center; margin-bottom: 18px;
    }
    .yb-popup-footer {
      color: #aaa;
      font-size: 0.8em;
      margin-top: 8px;
      margin-bottom: 4px;
      width: 100%;
      display: flex;
      justify-content: space-between;
    }
    .yb-popup-close {
      position: absolute;
      top: 10px; right: 16px;
      background: none;
      border: none;
      font-size: 2em;
      color: #bbb;
      cursor: pointer;
      transition: color 0.2s;
    }
    .yb-popup-close:hover {
      color: #f55;
    }
  `;

  // Add close functionality
  popup.querySelector('.yb-popup-close').onclick = function () {
    popup.remove();
  };

  // Add to page
  document.body.appendChild(popup);
  document.head.appendChild(style);
})();
